gridboard:
  do_qualize_hist: 0
  do_smoothing: 1
  bin_type: 1
  bin_param0: 50
  bin_param1: 0
  unitleng: 5.0
  n_circles_x: 20
  n_circles_y: 27
  origin_x: 10
  origin_y: 13
  distance_between_circles: 1.2
  n_circles_minimum: 4
  min_rate: 0.33
  max_rate: 1.5
  fitscore: 0.95
  fitrange: 1.5
  torelance: 1.5

robot:
  calib:
    bTc:
      translation:
        x: 1
        y: 1
        z: 0
      rotation:
        x: 0
        y: 0
        z: 0
        w: 1
    mTc:
      translation:
        x: 0.1
        y: 0.1
        z: 0
      rotation:
        x: 0
        y: 0
        z: 0
        w: 1
  position:
    cnt: 20
    rpos1:
      translation:
        x: 1020.007
        y: 1538.732
        z: 947.154
      rotation:
        x: 112.807
        y: -88.890
        z: 155.276
        w: 1
    rpos2:
      translation:
        x: 1053.607
        y: 1538.732
        z: 947.154
      rotation:
        x: 112.801
        y: -88.890
        z: 155.282
        w: 1
    rpos3:
      translation:
        x: 1020.007
        y: 1538.733
        z: 958.915
      rotation:
        x: 112.883
        y: -88.891
        z: 155.200
        w: 1
    rpos4:
      translation:
        x: 999.846
        y: 1538.732
        z: 947.154
      rotation:
        x: 112.805
        y: -88.890
        z: 155.278
        w: 1
    rpos5:
      translation:
        x: 1020.006
        y: 1538.731
        z: 930.354
      rotation:
        x: 112.801
        y: -88.890
        z: 155.281
        w: 1
    rpos6:
      translation:
        x: 1064.846
        y: 1512.830
        z: 947.155
      rotation:
        x: 113.016
        y: -88.888
        z: 162.013
        w: 1
    rpos7:
      translation:
        x: 1127.044
        y: 1476.902
        z: 947.156
      rotation:
        x: 112.805
        y: -88.890
        z: 171.859
        w: 1
    rpos8:
      translation:
        x: 913.973
        y: 1583.886
        z: 947.132
      rotation:
        x: 112.864
        y: -88.891
        z: 136.911
        w: 1
    rpos9:
      translation:
        x: 961.239
        y: 1560.153
        z: 947.137
      rotation:
        x: 113.512
        y: -88.884
        z: 144.003
        w: 1
    rpos10:
      translation:
        x: 993.730
        y: 1547.471
        z: 991.863
      rotation:
        x: 167.646
        y: -82.982
        z: 95.714
        w: 1
    rpos11:
      translation:
        x: 1020.010
        y: 1537.213
        z: 1028.038
      rotation:
        x: 173.357
        y: -77.927
        z: 94.827
        w: 1
    rpos12:
      translation:
        x: 1021.227
        y: 1560.659
        z: 878.882
      rotation:
        x: 4.504
        y: -81.083
        z: -96.528
        w: 1
    rpos13:
      translation:
        x: 1021.450
        y: 1564.958
        z: 851.537
      rotation:
        x: 2.547
        y: -77.271
        z: -94.581
        w: 1
    rpos14:
      translation:
        x: 1025.327
        y: 1518.816
        z: 1012.536
      rotation:
        x: -92.814
        y: -62.730
        z: 1.013
        w: 1
    rpos15:
      translation:
        x: 1066.205
        y: 1518.815
        z: 901.575
      rotation:
        x: 89.120
        y: -65.803
        z: 178.867
        w: 1
    rpos16:
      translation:
        x: 1189.818
        y: 1518.814
        z: 891.696
      rotation:
        x: 88.081
        y: 0.720
        z: 179.536
        w: 1
    rpos17:
      translation:
        x: 1046.890
        y: 1450.415
        z: 944.255
      rotation:
        x: 112.843
        y: -88.890
        z: 155.239
        w: 1
    rpos18:
      translation:
        x: 983.184
        y: 1511.844
        z: 991.781
      rotation:
        x: 162.825
        y: -82.586
        z: 97.248
        w: 1
    rpos19:
      translation:
        x: 1032.727
        y: 1527.933
        z: 1063.071
      rotation:
        x: -90.454
        y: -18.749
        z: -1.776
        w: 1
    rpos20:
      translation:
        x: 1078.963
        y: 1470.884
        z: 1108.490
      rotation:
        x: -90.436
        y: 9.651
        z: -1.995
        w: 1

