.PHONY: clean

CC=g++
CFLAGS= -c  -O3
LDFLAGS= 
TG=noise_reduct
OBJS=main.o noise_reduct.o voxel.o plyio.o point_mesh.o mycommons.o

$(TG) : $(OBJS)
	$(CC) -o $@ $(OBJS)

.c.o:
	$(CC) $(CFLAGS) -o$@ $<

clean:
	rm -f *.o $(TG)

